main/models.py
from django.db import models
from django.core.mail import send_mail
# Create your models here.
#

class Group(models.Model):
    name = models.CharField(max_length=256)
    def __unicode__(self):
        return self.name

class Entrant(models.Model):
    name = models.CharField(max_length=256)
    group = models.ForeignKey(Group)
    email = models.CharField(max_length=256)
    zip = models.CharField(max_length=256, default='', blank=True)
    city = models.CharField(max_length=256, default='', blank=True)
    state = models.CharField(max_length=256, default='', blank=True)
    street = models.CharField(max_length=256, default='', blank=True)
    match = models.ForeignKey('self', null=True, blank=True)
    cantget = models.ManyToManyField('self', null=True, blank=True)
    hint  =  models.TextField(default='', blank=True)

    def __unicode__(self):
        return self.name + ' -- ' + self.group.name

    def save(self, *args, **kwargs):
        needs_confirmation = False
        if not self.id:
            needs_confirmation = True
        super(Entrant, self).save(*args, **kwargs)
        if needs_confirmation:
            send_mail('Secret Santa', 'Just making sure you gave a valid email address. You\'ll get another email telling you about your victim after everyone signs up.'
                    , 'secretsanta@joelsemar.com', [self.email], fail_silently=True) 

main/views.py
# Create your views here.
from main.models import Entrant, Group
from django.http import HttpResponseRedirect
from django.core.mail import send_mail
from django.views.generic.simple import direct_to_template
import random
from consts import SUPPORTED_STATES as states


def home(request):
    groups = Group.objects.all()
    return  direct_to_template(request, 'index.html', extra_context={'states': states, 'groups': groups})



def submit(request):
    name = request.POST.get('name')
    group_name = request.POST.get('group')
    email = request.POST.get('email')
    street = request.POST.get('street')
    city = request.POST.get('city')
    state = request.POST.get('state')
    zip = request.POST.get('zip')
    hint = request.POST.get('hint')

    if not (email and name):
        request.session['error'] = "We at least need your email address and name."
        return HttpResponseRedirect('/')

    group = Group.objects.get(name=group_name)

    try:
       entrant = Entrant.objects.get(email=email, group=group)
       request.session['error'] = "That email has already signed up."
       return HttpResponseRedirect('/')
    except Entrant.DoesNotExist:
       Entrant.objects.create(email=email, name=name, city=city, zip=zip, street=street, state=state, hint=hint, group=group)

    request.session['message']  = "That wasn't so hard eh? You can come back here later to see who else has signed up"
    return HttpResponseRedirect('/')

def processor(request):
    ret = {}
    error = request.session.get('error')
    message = request.session.get('message')
    if error:
       ret['error'] = error
       del request.session['error']

    if message:
       ret['message'] = message
       del request.session['message']
    return ret


def make_matches(group_name):

    entrants = Entrant.objects.filter(group__name=group_name)
    entrant_list = list(entrants)

    for entrant in entrants:
        cantget = entrant.cantget.all()
        left = [e for e in entrant_list if e.id !=entrant.id and e not in cantget]
        if not left:
            return make_matches(group_name)
        choice = random.choice(left)
        entrant_list.remove(choice)
        entrant.match = choice

    for entrant in entrants:
        entrant.save()

def notify_entrants(group_name):

    entrants = Entrant.objects.filter(group__name=group_name).select_related('match')
    for entrant in entrants:
        notify_entrant(entrant)


def notify_entrant(entrant):
        match = entrant.match
        msg = """Alright, the results are in, here is your victim:

Name:    %(name)s
Address: %(street)s %(city)s, %(state)s %(zip)s

Here's what they said about what they want for christmas:

%(hint)s

        """ % {'name': match.name, 'street': match.street, 'city': match.city, 'state': match.state, 'zip': match.zip, 'hint': match.hint}
        send_mail('Secret Santa Results', msg, 'secretsanta@joelsemar.com', [entrant.email], fail_silently=True)

main/templates/index.html
<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/bootstrap.min.css">
<script type='application/javascript' src='http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js'></script>
<script type='application/javascript' src='{{STATIC_URL}}/bootstrap/js/bootstrap-alerts.js'></script>
<script type='application/javascript'>
    $(function(){
       $('.alert-message').alert();
     });
</script>
<title>Secret Santa</title>
</head>
<body style='margin-top: 60px'>
<div class='topbar'>
  <div class='topbar-inner'>
   <div class='container'>
    <div class='brand'> Secret Santa</div>
   </div>
 </div>
</div>
  <div class="container-fluid">
   <div class="sidebar">
    <div class='well'>
    <h5> Participants so far </h5>
     {% for group in groups %}
        <h2> {{group.name}} </h2>
        {% if not group.entrant_set.all %}
        No one has signed up so far 
        {%else %}
            <ul class='unstyled'>
        {% for entrant in group.entrant_set.all %}
            <li>{{entrant.name}}</li>
        {% endfor %}
        </ul>
        {% endif %}
     {% endfor %}
     </div>
    </div>
    <div class="content">
      <div class='hero-unit'>
        <h1> Secret Santa </h1>
        <p>Hundreds of days old tradition between the Fry, Semar and Van Broekhoven clans</p>
        {% if error %}
        <div class='alert-message error in fade out'>
         <a class='close' href='#'>x</a>
            {{error}}</div>
        {% endif %}
        {% if message %}
        <div class='alert-message success fade in'>
         <a class='close' href='#'>x</a>
            {{message}}</div>
        {% endif %}

        <form action='/submit/' method='POST' class='form-stacked'>
          {% csrf_token %}
         <fieldset>
          <legend> Sign up if you haven't already. </legend>
            <div class='clearfix'>

              <label for='group'>Group</label>
                  <div class='input'>
                  <select name='group'>
                      {% for group in groups %}
                      <option value='{{group.name}}'>{{group.name}}</option>
                      {% endfor %}
                  </select>
                  </div>

             <label for='name'>Name</label>
               
               <div class='input'>
                <input class='xlarge' name='name' size=40 type='text'></input>
                <span class='help-inline'>Required. </input>
               </div>
               <label for='name'>Email</label>
               <div class='input'>
                <input class='xlarge' name='email' size=40 type='text'></input>
                <span class='help-inline'>Required. </input>
              </div>
            </div>
         </fieldset>
         </hr>
         <fieldset>
           <legend> Don't make your santa have to track this down:</legend>
          <div class='clearfix'>
             <label for='street'>Street</label>
               <div class='input'>
                <input class='xlarge' name='street' size=40 type='text'></input>
              </div>
             <label for='city'>City</label>
               <div class='input'>
                <input class='xlarge' name='city' size=40 type='text'></input>
              </div>
              <label for='state'>State</label>
                  <div class='input'>
                  <select name='state'>
                      {% for state in states %}
                      <option value='{{state.abbrv}}'>{{state.name}}</option>
                      {% endfor %}
                  </select>
                  </div>
             <label for='zip'>Zip</label>
               <div class='input'>
                <input class='xlarge' name='zip' size=40 type='text'></input>
              </div>
            </div>
          </fieldset>
          <fieldset>
              <legend> And finally, give your santa a hint or a nudge in the right direction.</legend>
              <div class='clearfix'>
                  <label for='hint'>Hint:</label>
                    <textarea class='xxlarge' name='hint' rows='10'></textarea>
            </div>

          </fieldset>
          <div class = 'actions'>
          <button type='submit' class='btn primary'> Submit </button>
         </div>
       </form>
      </div>
    </div>
  </div>
</body>
</html>